"""email verification

Revision ID: 87f3143089b7
Revises: 9cac42c7b507
Create Date: 2026-08-05 18:55:32.768720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f3143089b7'
down_revision: Union[str, Sequence[str], None] = '9cac42c7b507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###

    # Everyone who signed up before confirmation existed is grandfathered in.
    # Leaving them NULL would do two wrong things at once: nag people to
    # confirm an address they have been receiving mail at for months, and —
    # because grant_signup_bonus pays out whenever email_verified_at is NULL —
    # hand every existing account a SECOND signup bonus the moment they
    # clicked. created_at rather than now(): these accounts were never
    # pending, so a wall of identical migration timestamps would misdate them.
    op.execute("UPDATE users SET email_verified_at = created_at WHERE email_verified_at IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_token_hash'))

    op.drop_table('email_verifications')
    # ### end Alembic commands ###
